name: M3U8 Extractor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run extractor
        run: node src/extract.js

      - name: Commit latest.m3u8
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add latest.m3u8
          git commit -m "update stream" || echo "no changes"
          git push
